### ISSUE TITLE
在Microsoft Edge下无效啊 

### ISSUE THREAD

**Issue by mingxiaoyu** [tete1030/github-repo-dispatcher#1]
如题。。。
不只是是GitHub 界面修改的问题，还是 Microsoft Edge 的问题。 发现无效

**Comment by tete1030** [comment]
怎么无效，是按钮不显示，还是触发没效果。你的edge是chromium版还是旧版？能否说下版本号。
如果”开发人员工具“显示任何错误，也请发一下。

**Comment by mingxiaoyu** [comment]
chromium版 应该是最新版 
按钮不显示

**Comment by mingxiaoyu** [comment]
F12要晚上才可以提供了  又又又在公车上

**Comment by mingxiaoyu** [comment]
我去。。。晚上回到家， 就好了

**Comment by tete1030** [comment]
确实偶尔会不显示，这个问题我也遇见过。这是因为github页面会延迟加载，延迟太久的话，页面还没准备好就尝试插入按钮。以后会改进
